default_language_version:
    python: python3.12

repos:
    - repo: https://github.com/pycqa/flake8
      rev: 7.0.0
      hooks:
          - id: flake8
            args:
                - --config=.code_quality/.flake8
            exclude: (tests|\.code_quality)

    - repo: https://github.com/pycqa/pylint
      rev: v3.0.3
      hooks:
          - id: pylint
            args:
                - --rcfile=.code_quality/.pylintrc
            exclude: (tests|\.code_quality|alembic/versions)
            verbose: true

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.1.14
      hooks:
          - id: ruff
            args:
                - --config=.code_quality/.ruff.toml
          - id: ruff-format
            args:
                - --config=.code_quality/.ruff.toml

    - repo: https://github.com/psf/black
      rev: 23.12.1
      hooks:
          - id: black
            args:
                - --line-length=120

    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
            args:
                - --profile=black
                - --line-length=120

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: debug-statements

    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.6
      hooks:
          - id: bandit
            args:
                - -c
                - .code_quality/bandit.yaml
            exclude: tests/.*

default_stages: [commit, manual]