line-length = 120
target-version = "py312"

[lint]
select = ["E", "F", "B", "I"]
ignore = ["E203", "E501", "I001"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"